/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YearlyRouteImport } from './routes/yearly'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as MonthlyRouteImport } from './routes/monthly'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiCronSyncReposRouteImport } from './routes/api/cron/sync-repos'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const YearlyRoute = YearlyRouteImport.update({
  id: '/yearly',
  path: '/yearly',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyRoute = MonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncReposRoute = ApiCronSyncReposRouteImport.update({
  id: '/api/cron/sync-repos',
  path: '/api/cron/sync-repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/monthly': typeof MonthlyRoute
  '/todos': typeof TodosRoute
  '/weekly': typeof WeeklyRoute
  '/yearly': typeof YearlyRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-repos': typeof ApiCronSyncReposRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/monthly': typeof MonthlyRoute
  '/todos': typeof TodosRoute
  '/weekly': typeof WeeklyRoute
  '/yearly': typeof YearlyRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-repos': typeof ApiCronSyncReposRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/monthly': typeof MonthlyRoute
  '/todos': typeof TodosRoute
  '/weekly': typeof WeeklyRoute
  '/yearly': typeof YearlyRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-repos': typeof ApiCronSyncReposRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily'
    | '/dashboard'
    | '/login'
    | '/monthly'
    | '/todos'
    | '/weekly'
    | '/yearly'
    | '/sitemap/xml'
    | '/api/auth/$'
    | '/api/cron/sync-repos'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily'
    | '/dashboard'
    | '/login'
    | '/monthly'
    | '/todos'
    | '/weekly'
    | '/yearly'
    | '/sitemap/xml'
    | '/api/auth/$'
    | '/api/cron/sync-repos'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/daily'
    | '/dashboard'
    | '/login'
    | '/monthly'
    | '/todos'
    | '/weekly'
    | '/yearly'
    | '/sitemap/xml'
    | '/api/auth/$'
    | '/api/cron/sync-repos'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyRoute: typeof DailyRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MonthlyRoute: typeof MonthlyRoute
  TodosRoute: typeof TodosRoute
  WeeklyRoute: typeof WeeklyRoute
  YearlyRoute: typeof YearlyRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronSyncReposRoute: typeof ApiCronSyncReposRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yearly': {
      id: '/yearly'
      path: '/yearly'
      fullPath: '/yearly'
      preLoaderRoute: typeof YearlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly': {
      id: '/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof MonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-repos': {
      id: '/api/cron/sync-repos'
      path: '/api/cron/sync-repos'
      fullPath: '/api/cron/sync-repos'
      preLoaderRoute: typeof ApiCronSyncReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyRoute: DailyRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MonthlyRoute: MonthlyRoute,
  TodosRoute: TodosRoute,
  WeeklyRoute: WeeklyRoute,
  YearlyRoute: YearlyRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronSyncReposRoute: ApiCronSyncReposRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
